name: full-build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build 11ty
        uses: TartanLlama/actions-eleventy@master
      - name: gh-pages deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./ 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
